// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../ts-postgres-model
//   ../ts-express-controller
//   ../express
//   ../bookshelf
//   ../knex

import { IPostgresModelClass, PostgresModel } from "ts-postgres-model";
import { Controller } from 'ts-express-controller';
import { Response } from 'express';
import * as e from "express";
import { IUser } from "ts-postgres-model";
import { Collection } from 'bookshelf';
import { Transaction } from 'knex';

/**
    * Default GET by ID
    */
export class GetRoute extends Controller {
        constructor(_type: IPostgresModelClass<any>, idParamName: string);
        protected handleRequest(params: any, req: IUserRequest, res: Response): Promise<any>;
}
/**
    * Default POST from request JSON body
    */
export class PostRoute extends Controller {
        constructor(_type: IPostgresModelClass<any>);
        protected handleRequest(params: any, req: IUserRequest, res: Response): Promise<any>;
}
/**
    * Default PUT by ID from request JSON body
    */
export class PutByIdRoute<T extends PostgresModel<T>> extends Controller {
        constructor(_type: IPostgresModelClass<any>, idParamName: string);
        protected handleRequest(params: any, req: IUserRequest, res: Response): Promise<any>;
}
/**
    * Default PATCH by ID from request JSON body
    */
export class PatchByIdRoute<T extends PostgresModel<T>> extends Controller {
        constructor(_type: IPostgresModelClass<any>, idParamName: string);
        protected handleRequest(params: any, req: IUserRequest, res: Response): Promise<any>;
}
/**
    * Default PUT by ID from request JSON body
    */
export class MultiPutRoute<T extends PostgresModel<T>> extends Controller {
        constructor(_type: IPostgresModelClass<any>);
        protected handleRequest(params: any, req: IUserRequest, res: Response): Promise<any>;
}
/**
    * Default PUT by ID from request JSON body
    */
export class MultiPatchRoute<T extends PostgresModel<T>> extends Controller {
        constructor(_type: IPostgresModelClass<any>);
        protected handleRequest(params: any, req: IUserRequest, res: Response): Promise<any>;
}
/**
    * Default DELETE by ID
    */
export class DeleteRoute extends Controller {
        constructor(_type: IPostgresModelClass<any>, idParamName: string);
        protected handleRequest(params: any, req: IUserRequest, res: Response): Promise<void>;
}
/**
    * Default Query for all objects of a type
    */
export class QueryRoute extends Controller {
        constructor(_type: IPostgresModelClass<any>, fetchParams?: any, _allowDeleted?: boolean | undefined);
        protected handleRequest(params: any, req: IUserRequest, res: Response): Promise<any[]>;
}
export class MarkDeletedRoute extends Controller {
        constructor(_type: IPostgresModelClass<any>, idParamName: string);
        protected handleRequest(params: any, req: IUserRequest, res: Response): Promise<any>;
}
export class MarkUndeletedRoute extends Controller {
        constructor(_type: IPostgresModelClass<any>, idParamName: string);
        protected handleRequest(params: any, req: IUserRequest, res: Response): Promise<any>;
}

export interface IUserRequest extends e.Request {
    user: IUser;
}

export class CrudHandlers {
    static postFromRequestBody<T extends PostgresModel<T>>(req: IUserRequest, model: IPostgresModelClass<T>): Promise<any>;
    static getObjectById<T extends PostgresModel<T>>(req: IUserRequest, model: IPostgresModelClass<T>, objectId: number): Promise<T>;
    static putObject<T extends PostgresModel<T>>(req: IUserRequest, model: IPostgresModelClass<T>, objectId: number, transaction?: Transaction): Promise<T>;
    static patchObject<T extends PostgresModel<T>>(req: IUserRequest, model: IPostgresModelClass<T>, objectId: number, transaction?: Transaction): Promise<T>;
    static putObjects<T extends PostgresModel<T>>(req: IUserRequest, model: IPostgresModelClass<T>, transaction?: Transaction): Promise<T | Collection<T>>;
    static patchObjects<T extends PostgresModel<T>>(req: IUserRequest, model: IPostgresModelClass<T>, transaction?: Transaction): Promise<T | Collection<T>>;
    static deleteObject<T extends PostgresModel<T>>(req: IUserRequest, model: IPostgresModelClass<T>, objectId: number): Promise<void>;
    static setObjectDeleted<T extends PostgresModel<T>>(req: IUserRequest, model: IPostgresModelClass<T>, objectId: number): Promise<T>;
    static setObjectUndeleted<T extends PostgresModel<T>>(req: IUserRequest, model: IPostgresModelClass<T>, objectId: number): Promise<T>;
}

export class CrudConfig {
    static setControllerConfig(name: string, description: string, version: string): void;
}

